In [17]:
import numpy as np
import sys

l = [1, 2, 3, 4]
print(sys.getsizeof(1) * len(l))

# Numpy array creating methods
my_arr = np.array([1,2,3,4])
print(my_arr.itemsize * my_arr.size)
print(my_arr)

112
16
[1 2 3 4]


In [4]:
a1 = np.arange(9).reshape(3, 3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
a2 = np.ones((3, 4), dtype = int) #default dtype = float64
a3 = np.ones((2, 2), np.int64)
a2
a3.shape

(2, 2)

In [13]:
a4 = np.zeros((2, 2), dtype = int)
a4

array([[0, 0],
       [0, 0]])

In [15]:
a5 = np.empty((4, 3))
a5.ravel() # flattens into 1-D

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
a6 = np.linspace(1, 10, 8)
a6

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [23]:
a7 = np.array(np.mat('[1, 2]; [3, 4]'), subok=True)
a7

array([[1, 2],
       [3, 4]])

In [1]:
# from numpy import array
import numpy as np

a1 = np.array([[1, 2, 3],
                [2, 0, 2],
                [1, 2, 1]])
a2 = np.array([[2, 8, 1],
                [1, 2, 3],
                [1, 0, 1]])
a1.dot(a2)

array([[ 7, 12, 10],
       [ 6, 16,  4],
       [ 5, 12,  8]])