In [15]:
import numpy as np
import sys

a = [1, 2, 3, 4]
print(sys.getsizeof(1) * len(a))
my_arr = np.array(a)
my_arr
print(my_arr.itemsize * my_arr.size)

112
16


In [23]:
m1 = np.arange(9).reshape(3,3)
print(m1)
m2 = np.arange(3,12).reshape(3,3)
print(m2)

print(m1 * m2) # element wise product
print(np.dot(m1,m2)) #matrix product
print(np.trace(m1))
print(m1.trace())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  4 10]
 [18 28 40]
 [54 70 88]]
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]
12
12


In [26]:
a1 = np.array(np.mat('[1 2 3]; [4 2 0]; [2 0 1]'))
a1.T
a1.transpose()

array([[1, 4, 2],
       [2, 2, 0],
       [3, 0, 1]])

In [31]:
z1 = np.ones((3,3))
z1
z1.argmax(axis=0)
z1.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [38]:
r1 = np.random.random(9).reshape(3,3)
print(r1)
r1.min()

[[0.08214447 0.35316106 0.94131746]
 [0.63967481 0.08516993 0.0540903 ]
 [0.2814493  0.93421758 0.27944414]]


0.9413174633818695

In [40]:
r1.max()

0.9413174633818695

In [44]:
r1.sort()
r1

array([[0.08214447, 0.35316106, 0.94131746],
       [0.0540903 , 0.08516993, 0.63967481],
       [0.27944414, 0.2814493 , 0.93421758]])

In [46]:
np.corrcoef(r1)

array([[1.        , 0.96471297, 0.95203691],
       [0.96471297, 1.        , 0.99900889],
       [0.95203691, 0.99900889, 1.        ]])

In [47]:
n = np.array([[1,2,3],
             [2,3,5],
             [0,1,4]])
np.mean(n)

2.3333333333333335

In [48]:
np.median(n)

2.0

In [49]:
np.std(n)

1.4907119849998598

In [52]:
np.percentile(n,25)

1.0