In [2]:
import numpy as np
import sys

a = [1.2, 3.3, 4.4, 5.1]
print(a)
print('size', sys.getsizeof(a))
N_arr = np.asarray(a)
print(N_arr)
print('size', N_arr.itemsize * N_arr.size)

[1.2, 3.3, 4.4, 5.1]
size 88
[1.2 3.3 4.4 5.1]
size 32


In [8]:
a = np.arange(20)
print(a[1:])
print(a[1:10])
print(a[0:15:2])
print(a[17:0:-2])
print(a[-7:19:1])

#integer Indexing
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a[[0,1], [1,1]])
print(a[[0, 1, 2], [1, 1, 1]])

#Boolean indexing
b = np.arange(0, 30, 2).reshape(3,5)
print(b)
print(b[b>10])

print(b[b%5 == 0])

b.sum(axis = 1)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14]
[17 15 13 11  9  7  5  3  1]
[13 14 15 16 17 18]
[2 5]
[2 5 8]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[12 14 16 18 20 22 24 26 28]
[ 0 10 20]


array([ 20,  70, 120])

In [9]:
arr = np.arange(20).reshape(2, 10)
print(arr)
print(arr.max(axis = 0))
print(arr.min())
print(arr.sum(axis = 1))
print(arr.cumsum())

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[10 11 12 13 14 15 16 17 18 19]
0
[ 45 145]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]


In [59]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(3, 2)
2
6
int32
